  ---
title: "Metabolomics Analysis"
author: "Jacob Agerbo Rasmussen"
date: "10/22/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load dependencies, include=FALSE}
library(ggplot2)
library(readxl)
library(phyloseq)
library(ape)
library(dplyr)
library(MetaboDiff)
```

```{r load data}
# Load data
ft <- read.csv("MS1_curated.csv")
rt_mz <- ft[,1:3]
rownames(ft) <- ft[,1]
ft <- ft[,4:63]

tax <- read_excel("Chemical_Class.xlsx")
md <- read.csv("metadata.csv")
MetDNA <- read.csv("HF_pseudomonas_MRN.annotation.result.csv")

My_pal <- c("#3889A0","#F2AD00","#9C964A","#D95F02","#1B9E77","#046C9A","#0B775E","#35274A","#F2300F","#666666") 
group_pal <- c("#e3aa74", "#ed828c", "#7bb6bd")
```

```{r Curate tax files}
tax <- tax[match(rownames(ft),tax$ID),]
MetDNA <- MetDNA[match(rownames(ft),MetDNA$name),]
cmp <- MetDNA$compound.name
Ant <- cbind(tax,cmp)
Ant <- as.matrix(Ant)
rownames(Ant) <- Ant[,1]
rownames(md) <- colnames(ft)
Ant <- as.data.frame(Ant)
Ant$Annotation <- paste(Ant$Compound_Name,Ant$cmp)

#is.na(Ant$ID)
Ant <- Ant[-c(253),]

names <- Ant$ID
Ant <- as.matrix(Ant)
rownames(Ant) <- names
```

```{r generate phyloseq elements, because phyloseq is genious for this type of abundance data}
# physeq element
physeq <- phyloseq(otu_table(ft, taxa_are_rows = TRUE), tax_table(Ant),sample_data(md))
random_tree = rtree(ntaxa(physeq), rooted=TRUE, tip.label=taxa_names(physeq))
plot(random_tree)
physeq = merge_phyloseq(physeq, random_tree)
physeq.sort = transform_sample_counts(physeq, function(x) x/sum(x))
Myco_x_meta = subset_samples(physeq.sort, Keep=="Yes")
```
```{r NMDS/PCOA plot - sum normalised}
#r NMDS/PCOA plot - sum normalised
GP.ord <- ordinate(physeq, "PCoA", "jaccard")
p1 = plot_ordination(physeq, GP.ord, type="samples", color="Feed") 
#pdf("jaccard_ordination_metabolites.pdf", height = 12, width = 12)
p1 + geom_point(size=4) + theme_minimal() + scale_fill_manual(values = group_pal) +
  scale_color_manual(values = group_pal)
#dev.off()

GP.ord <- ordinate(Myco_x_meta, "PCoA", "jaccard")
p2 = plot_ordination(Myco_x_meta, GP.ord, type="samples", color="Feed") 
#pdf("jaccard_ordination_metabolites_x_mycoplasma.pdf", height = 8, width = 12)
md_ord <- md[md$Keep == "Yes",]
p2 + geom_point(size=7.5, alpha = as.numeric(md_ord$Mycoplasma)) + 
  theme_minimal() + scale_fill_manual(values = group_pal) +
  scale_color_manual(values = group_pal)
#dev.off()



```

```{r Class specific Ordination}
Myco_x_meta_Class <- subset_taxa(Myco_x_meta, CF_subclass=="Amino acids, peptides, and analogues")
GP.ord <- ordinate(Myco_x_meta_Class, "PCoA", "jaccard")
p2 = plot_ordination(Myco_x_meta_Class, GP.ord, type="samples", color="Feed") 
md_ord <- md[md$Keep == "Yes",]
p_AA =p2 + geom_point(size=7.5, alpha = as.numeric(md_ord$Mycoplasma)) + 
  theme_minimal() + scale_fill_manual(values = group_pal) +
  scale_color_manual(values = group_pal)

Myco_x_meta_Class <- subset_taxa(Myco_x_meta, CF_superclass=="Lipids and lipid-like molecules")
GP.ord <- ordinate(Myco_x_meta_Class, "PCoA", "jaccard")
p2 = plot_ordination(Myco_x_meta_Class, GP.ord, type="samples", color="Feed") 
md_ord <- md[md$Keep == "Yes",]
p_Lipids =p2 + geom_point(size=7.5, alpha = as.numeric(md_ord$Mycoplasma)) + 
  theme_minimal() + scale_fill_manual(values = group_pal) +
  scale_color_manual(values = group_pal)

Myco_x_meta_Class <- subset_taxa(Myco_x_meta, CF_subclass=="Bile acids, alcohols and derivatives")
GP.ord <- ordinate(Myco_x_meta_Class, "PCoA", "jaccard")
p2 = plot_ordination(Myco_x_meta_Class, GP.ord, type="samples", color="Feed") 
md_ord <- md[md$Keep == "Yes",]
p_Bile =p2 + geom_point(size=7.5, alpha = as.numeric(md_ord$Mycoplasma)) + 
  theme_minimal() + scale_fill_manual(values = group_pal) +
  scale_color_manual(values = group_pal)

Myco_x_meta_Class <- subset_taxa(Myco_x_meta, CF_class =="Steroids and steroid derivatives")
GP.ord <- ordinate(Myco_x_meta_Class, "PCoA", "jaccard")
p2 = plot_ordination(Myco_x_meta_Class, GP.ord, type="samples", color="Feed") 
md_ord <- md[md$Keep == "Yes",]
p_Steroids =p2 + geom_point(size=7.5, alpha = as.numeric(md_ord$Mycoplasma)) + 
  theme_minimal() + scale_fill_manual(values = group_pal) +
  scale_color_manual(values = group_pal)

#pdf("jaccard_ordination_metabolites_x_mycoplasma_classes.pdf", height = 8, width = 12)
cowplot::plot_grid(p_AA,
                   p_Lipids,
                   p_Bile,
                   p_Steroids,
                   labels = c('Amino acids, peptides, and analogues', 'Lipids and lipid-like molecules',
                              'Bile acids, alcohols and derivatives','Steroids and steroid derivatives'), ncol = 2)
#dev.off()

```

```{r}
Myco_x_meta <- subset_samples(physeq, Keep=="Yes")
Myco_x_meta_1 = subset_samples(Myco_x_meta, Replicate=="1")

Myco_x_meta_2 = subset_samples(Myco_x_meta, Replicate=="2")

ft_table_1 <- Myco_x_meta_1@otu_table@.Data
ft_table_2 <- Myco_x_meta_2@otu_table@.Data

ft_tax <- Myco_x_meta_1@tax_table@.Data

md_rep_1 <- as.data.frame(Myco_x_meta_1@sam_data@.Data)
md_rep_2 <- as.data.frame(Myco_x_meta_2@sam_data@.Data)
colnames(md_rep_1) <- colnames(md)
colnames(md_rep_2) <- colnames(md)


#write.csv(ft_tax,"ft_tax.csv")
#write.csv(ft_table_1,"ft_table_rep_1.csv")
#write.csv(ft_table_2,"ft_table_rep_2.csv")
#write.csv(md_rep_1,"md_rep_1.csv")
#write.csv(md_rep_2,"md_rep_2.csv")
```


This is a home knitted version of a differential abundance test
```{r - Differential Abundance testing - Categorical - w/ Kruskal Wallis}
library("beeswarm")
ft.diff <- t(ft)
md.diff <- md

### Choose category for differential abbundance testing
cats <- droplevels(as.factor(md.diff$Feed_Additives))
cats
ftt <- t(apply(ft.diff, 1, function(x) (x)/sum((x))))
ftt[1:5,1:5]

### Define function
krusk <- function (x) {
  out <- tryCatch(unlist(kruskal.test(scale(ftt[,x])[,1] ~ as.factor(cats))[c("p.value")]), error = function(e) return(NA))
  return(out)
}

###
corres <- t(sapply(1:ncol(ftt), krusk ))
corres <- cbind(unlist(corres[1,]),p.adjust(unlist(corres[1,]), method = "fdr"))

rownames(corres) <- colnames(ftt)
corres <- cbind(corres,rownames(corres))
colnames(corres) <- c('p.value','p.value.corrected','feature id')
```
```{r write out table of all p values}
#write.table(corres, 'DifferentialAbundance.txt', sep = '\t', quote = F, row.names = F)
```
```{r - choose only significant adjusted p-values and create boxplots for each comparison}
length(which(as.numeric(corres[,2]) < 0.05))
corressig <- corres[which(as.numeric(corres[,2]) < 0.05),]

ftplot <- ftt

par(mfrow = c(2,3))
  for (i in 1:length(rownames(corressig))){
    selid <- rownames(corressig)[i]
    comp <- ftplot[,which(colnames(ftplot) == selid)]
    
    df <- cbind(as.character(md.diff$Feed),comp)
    colnames(df) <- c('SampleGroup','Summed Precursor Ion Intensities/MS2 Ion')
    df <- as.data.frame(df)
    df$SampleGroup <- as.character(df$SampleGroup)
    df$`Summed Precursor Ion Intensities/MS2 Ion` <- as.numeric(as.character(df$`Summed Precursor Ion Intensities/MS2 Ion`))
    
    #boxplot(`Summed Precursor Ion Intensities/MS2 Ion` ~ SampleGroup, data = df, outline = FALSE, main = selid)
    #beeswarm(`Summed Precursor Ion Intensities/MS2 Ion` ~ SampleGroup, data = df, col = c(4,2), pch = 16, add = TRUE)
}
#dev.off()
```
```{r}
library(ggpubr)
library(rstatix)
sig_tax <- Ant[order(match(rownames(corressig), Ant[,1])),]
st <- sig_tax[,c(1,8,9)]

data_sig <- cbind(corressig,st)

data <- cbind(corressig,st)
data <- as.data.frame(data)
data$Annotation <- paste(data$Compound_Name,data$cmp)
data <- data[data$Annotation != "NA NA",]
krusk_data <- data
```
```{r - choose only significant adjusted p-values and create boxplots for each comparison}
plot_list = list()
for (i in 1:length(rownames(data))){
    selid <- rownames(corressig)[i]
    comp <- ftplot[,which(colnames(ftplot) == selid)]
    
    df <- cbind(as.character(md.diff$Feed),comp)
    colnames(df) <- c('SampleGroup','Summed Precursor Ion Intensities/MS2 Ion')
    df <- as.data.frame(df)
    df$SampleGroup <- as.character(df$SampleGroup)
    df$`Summed Precursor Ion Intensities/MS2 Ion` <- as.numeric(as.character(df$`Summed Precursor Ion Intensities/MS2 Ion`))
    
    #boxplot(`Summed Precursor Ion Intensities/MS2 Ion` ~ SampleGroup, data = df, outline = FALSE, main = data$Annotation[i], col = group_pal)
    #beeswarm(`Summed Precursor Ion Intensities/MS2 Ion` ~ SampleGroup, data = df, col = "black", pch = 16, add = TRUE)
    # Add p-values onto the box plots
    stat.test <- df %>%
      group_by("SampleGroup") %>%
      wilcox_test(`Summed Precursor Ion Intensities/MS2 Ion` ~ SampleGroup) %>%
      adjust_pvalue(method = "fdr") %>%
      add_significance("p.adj")
    stat.test <- stat.test %>%
      add_x_position(x = "SampleGroup", dodge = 0.8) %>%
      add_y_position()
    # Create a box plot
    p = ggboxplot(
      df, x = "SampleGroup", y = "Summed Precursor Ion Intensities/MS2 Ion", 
      color = "black",
      fill = "SampleGroup", palette = group_pal,
      outlier.shape = 8,
      size = 0.5,
      title = data$Annotation[i])  + 
      stat_pvalue_manual(
        stat.test,  label = "{p.adj} {p.adj.signif}", tip.length = 0.02,
        step.increase = 0.075, 
        bracket.nudge.y = max(df$`Summed Precursor Ion Intensities/MS2 Ion`))
    plot_list[[i]] = p
}
```
```{r}
#pdf("Boxplot_of_significant_compounds_w_sig.pdf")
plot_list
#dev.off()
```

```{r - }
met <- create_mae(ft,tax,md)
md$Feed_Additives
```
```{r - Metabodiff normalization}
met = knn_impute(met,cutoff=0.4)
met <- normalize_met(met)
quality_plot(met,
             group_factor="Feed_Additives",
             label_colors=group_pal)
```
```{r - Metabodiff diff test}
met = diff_test(met,
                group_factors = c("Feed","Feed_Additives"))
str(metadata(met), max.level=2)
```
```{r plot differential test, using Enhanced volcano}
#df <- met@metadata[["anova_Feed_CTRL_vs_Probiotics_vs_Synbiotics"]]
df <- met@metadata[["ttest_Feed_Additives_Yes_vs_No"]]

df$Metabolites <- as.integer(rownames(met@ExperimentList@listData[["raw"]]@assays@data@listData[[1]]))

tax_diff <-  tax[order(match(df$Metabolites,rownames(tax))),]
df <- cbind(df,tax)

df_sig <- df[df$adj_pval<0.5,]

library(EnhancedVolcano)
p1 = EnhancedVolcano(df,
    lab = df$Compound_Name,
    boxedLabels = FALSE,
    x = 'fold_change',
    y = 'adj_pval',
    xlim = c(-5,5),
    pCutoff = 10e-2,
    FCcutoff = 1.0,
    labSize = 3,
    pointSize = c(ifelse(df$adj_pval<10e-3, 5, 1)),
    title = 'Differential Abundance of metabolites related to feed',
    legendPosition = 'bottom')
p1

save.image(file = "Metabolomics_Analysis.RData")

#pdf("Differential Abundance of metabolites MetaboDiff template.pdf", height = 7.5, width = 15)
#cowplot::plot_grid(p1, ncol = 1)
#dev.off()

#write.csv(df,file = "Diff_test_Metabodiff.csv")
#write.csv(df_sig,file = "Sig_Diff_test_Metabodiff.csv")
```
